// Gedeelde productdata voor LEDsation — gebruikt door de assortiments- en productpagina's.
window.LEDSATION_PRODUCTS = [
  {
    id: "finesation", name: "Puresation", cat: "binnen", category: "BINNEN · FIJN",
    tagColor: "#2DF5A6", glow: "rgba(45,245,166,0.14)", pitch: "P2.6",
    desc: "Fijne pixelpitch voor haarscherpe beelden op korte kijkafstand.",
    long: "Puresation is onze scherpste binnen-LED-wall. Met een pixelpitch van 2,6 mm blijft elk beeld tot vlak voor het scherm haarscherp — ideaal voor keynotes, presentaties en beursstands waar je publiek dichtbij staat.",
    specs: [["Pixelpitch", "2.6 mm"], ["Helderheid", "1.200 nits"], ["Kast", "500×500 mm"], ["Refresh", "3.840 Hz"], ["Kijkhoek", "160°"], ["Montage", "Hangend / staand"]],
    uses: ["Corporate", "Beurs", "Keynote"],
    features: ["Naadloze module-overgangen", "Fabriekskalibratie voor egale kleur", "Lichtgewicht die-cast kasten", "Snelle op- en afbouw met quick-locks"],
    price: "vanaf € 195", priceUnit: "per m² / dag",
    img: "products/Finesation.jpg", source: null,
  },
  {
    id: "elevsation", name: "Grandsation", cat: "binnen", category: "BINNEN · GROOT",
    tagColor: "#2DF5A6", glow: "rgba(45,245,166,0.12)", pitch: "P3.9",
    desc: "Veelzijdige allrounder voor grote zalen en podia.",
    long: "Grandsation tilt elk podium naar een hoger niveau. De lichtgewicht 500×1000 mm-kasten bouw je razendsnel op tot een groot beeldvlak, perfect als achtergrond voor award shows, congressen en optredens.",
    specs: [["Pixelpitch", "3.9 mm"], ["Helderheid", "1.500 nits"], ["Kast", "500×1000 mm"], ["Refresh", "3.840 Hz"], ["Kijkhoek", "160°"], ["Montage", "Hangend / grond"]],
    uses: ["Zaal", "Podium", "Award show"],
    features: ["Grote beeldvlakken in korte tijd", "Stabiele hangconstructie", "Egale helderheid over het hele vlak", "Compatibel met live videobronnen"],
    price: "vanaf € 145", priceUnit: "per m² / dag",
    img: "products/Elevsation.jpg", source: null,
  },
  {
    id: "solsation", name: "Sunsation", cat: "buiten", category: "BUITEN · IP65",
    tagColor: "#F2A65A", glow: "rgba(242,166,90,0.14)", pitch: "P4.8",
    desc: "Weerbestendig en extra helder, ook bij fel daglicht.",
    long: "Sunsation trotseert de elementen. Met 5.500 nits en IP65-bescherming blijft je beeld helder in de volle zon én droog bij regen — de vaste keuze voor festivals, buitenpodia en sportevenementen.",
    specs: [["Pixelpitch", "4.8 mm"], ["Helderheid", "5.500 nits"], ["Bescherming", "IP65"], ["Kast", "500×1000 mm"], ["Refresh", "3.840 Hz"], ["Montage", "Grond / truss"]],
    uses: ["Festival", "Buiten", "Concert"],
    features: ["IP65 weerbescherming voor- en achterzijde", "Extra hoge helderheid tegen zonlicht", "Robuuste, transportbestendige kasten", "Snel te koppelen voor grote oppervlakken"],
    price: "vanaf € 165", priceUnit: "per m² / dag",
    img: "products/Solsation.jpg", source: null,
  },
  {
    id: "rotasation", name: "Kinesation", cat: "creatief", category: "CREATIEF · ROTEREND",
    tagColor: "#8A6BF2", glow: "rgba(138,107,242,0.16)", pitch: "Roterend",
    desc: "Vijf gekoppelde panelen die mechanisch roteren voor een dynamisch blikvangereffect.",
    long: "Kinesation is pure beweging. Vijf gekoppelde panelen draaien mechanisch en creëren een hypnotiserend, dynamisch beeld dat blijft boeien — dé eyecatcher voor etalages, entrees en merkactivaties.",
    specs: [["Type", "Mechanisch roterend"], ["Schermen", "5 gekoppeld"], ["Beweging", "Roterend"], ["Montage", "Hangend"], ["Besturing", "Gesynchroniseerd"], ["Toepassing", "Binnen"]],
    uses: ["Etalage", "Entree", "Blikvanger"],
    features: ["Vijf synchroon roterende panelen", "Opvallende beweging trekt de aandacht", "Programmeerbare content per paneel", "Complete montage inclusief ophangframe"],
    price: "vanaf € 1.250", priceUnit: "per dag",
    img: "products/Roto-Five.jpg", source: "https://www.lanyiled.com/products/PRODUCTS/Five-connected-screens.html",
  },
  {
    id: "postersation", name: "Slimsation", cat: "binnen", category: "BINNEN · POSTER",
    tagColor: "#2DF5A6", glow: "rgba(45,245,166,0.14)", pitch: "Poster",
    desc: "Slank staand LED-posterscherm voor wandmontage.",
    long: "Slimsation vervangt je papieren poster door levend beeld. Dit slanke, staande LED-scherm hang je aan de wand en bedien je op afstand — wissel promoties met één druk en plan automatisch aan/uit. Perfect voor retail en showrooms.",
    specs: [["Montage", "Wandmontage"], ["Formaat", "Staand (portret)"], ["Bediening", "Op afstand"], ["Content", "Geplande rotatie"], ["Verbruik", "Laag"], ["Beeld", "Full HD"]],
    uses: ["Retail", "Showroom", "Reclame"],
    features: ["Content wisselen met één druk op afstand", "Geplande aan/uit-tijden", "Slank profiel, bespaart vloerruimte", "Laag verbruik voor continu gebruik"],
    price: "vanaf € 95", priceUnit: "per dag",
    img: "products/Poster-Wall.jpg", source: "https://www.lanyiled.com/products/LED-Poster-Screen/Wall-Mounted-Poster-Display.html",
  },
  {
    id: "floorsation", name: "Foundsation", cat: "creatief", category: "CREATIEF · VLOER",
    tagColor: "#1FD8E6", glow: "rgba(31,216,230,0.16)", pitch: "Vloer",
    desc: "Vloerstaand LED-scherm dat zichzelf presenteert zonder ophangconstructie.",
    long: "Foundsation zet je overal neer waar je een blikvanger wilt. Het scherm staat vrij op de vloer zonder truss of ophangframe, dus je verplaatst het zo naar een nieuwe plek — ideaal als mobiele eyecatcher op beurzen en in winkels.",
    specs: [["Montage", "Vloerstaand"], ["Type", "Staand paneel"], ["Opbouw", "Zonder truss"], ["Mobiel", "Ja"], ["Toepassing", "Binnen"], ["Verplaatsen", "Eenvoudig"]],
    uses: ["Beurs", "Winkel", "Promotie"],
    features: ["Vrijstaand, geen ophangconstructie nodig", "Snel te verplaatsen tussen locaties", "Stabiele voet voor veilig gebruik", "Klaar voor gebruik in enkele minuten"],
    price: "vanaf € 175", priceUnit: "per dag",
    img: "products/Floor-Panel.jpg", source: "https://www.lanyiled.com/products/PRODUCTS/Floor-mounted-LED-screen.html",
  },
];